# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/cr_ce.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/cr_ce.proto',
  package='ghost',
  syntax='proto2',
  serialized_pb=_b('\n\x1aghost_protocol/cr_ce.proto\x12\x05ghost\"\xbc\x03\n\rCR_CE_Devices\x12\x33\n\nip_devices\x18\x01 \x01(\x0b\x32\x1f.ghost.CR_CE_Devices.IP_Devices\x12:\n\nbt_devices\x18\x02 \x01(\x0b\x32&.ghost.CR_CE_Devices.Bluetooth_Devices\x12\x36\n\nzw_devices\x18\x03 \x01(\x0b\x32\".ghost.CR_CE_Devices.ZWave_Devices\x12\x36\n\nrf_devices\x18\x04 \x01(\x0b\x32\".ghost.CR_CE_Devices.RF869_Devices\x12\x37\n\nzb_devices\x18\x05 \x01(\x0b\x32#.ghost.CR_CE_Devices.Zigbee_Devices\x1a\x18\n\nIP_Devices\x12\n\n\x02ip\x18\x01 \x03(\t\x1a\x1f\n\x11\x42luetooth_Devices\x12\n\n\x02\x62t\x18\x01 \x03(\t\x1a\x1b\n\rZWave_Devices\x12\n\n\x02zw\x18\x01 \x03(\t\x1a\x1b\n\rRF869_Devices\x12\n\n\x02rf\x18\x01 \x03(\t\x1a\x1c\n\x0eZigbee_Devices\x12\n\n\x02zb\x18\x01 \x03(\t\"^\n\x0bReducedData\x12\x32\n\x0b\x64\x65vice_data\x18\x01 \x03(\x0b\x32\x1d.ghost.ReducedData.DeviceData\x1a\x1b\n\nDeviceData\x12\r\n\x05value\x18\x01 \x03(\x01\x42\x1c\n\x1a\x65u.ghost_iot.communication')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CR_CE_DEVICES_IP_DEVICES = _descriptor.Descriptor(
  name='IP_Devices',
  full_name='ghost.CR_CE_Devices.IP_Devices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='ghost.CR_CE_Devices.IP_Devices.ip', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=361,
)

_CR_CE_DEVICES_BLUETOOTH_DEVICES = _descriptor.Descriptor(
  name='Bluetooth_Devices',
  full_name='ghost.CR_CE_Devices.Bluetooth_Devices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bt', full_name='ghost.CR_CE_Devices.Bluetooth_Devices.bt', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=394,
)

_CR_CE_DEVICES_ZWAVE_DEVICES = _descriptor.Descriptor(
  name='ZWave_Devices',
  full_name='ghost.CR_CE_Devices.ZWave_Devices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zw', full_name='ghost.CR_CE_Devices.ZWave_Devices.zw', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=423,
)

_CR_CE_DEVICES_RF869_DEVICES = _descriptor.Descriptor(
  name='RF869_Devices',
  full_name='ghost.CR_CE_Devices.RF869_Devices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rf', full_name='ghost.CR_CE_Devices.RF869_Devices.rf', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=452,
)

_CR_CE_DEVICES_ZIGBEE_DEVICES = _descriptor.Descriptor(
  name='Zigbee_Devices',
  full_name='ghost.CR_CE_Devices.Zigbee_Devices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zb', full_name='ghost.CR_CE_Devices.Zigbee_Devices.zb', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=482,
)

_CR_CE_DEVICES = _descriptor.Descriptor(
  name='CR_CE_Devices',
  full_name='ghost.CR_CE_Devices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_devices', full_name='ghost.CR_CE_Devices.ip_devices', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bt_devices', full_name='ghost.CR_CE_Devices.bt_devices', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zw_devices', full_name='ghost.CR_CE_Devices.zw_devices', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rf_devices', full_name='ghost.CR_CE_Devices.rf_devices', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zb_devices', full_name='ghost.CR_CE_Devices.zb_devices', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CR_CE_DEVICES_IP_DEVICES, _CR_CE_DEVICES_BLUETOOTH_DEVICES, _CR_CE_DEVICES_ZWAVE_DEVICES, _CR_CE_DEVICES_RF869_DEVICES, _CR_CE_DEVICES_ZIGBEE_DEVICES, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=482,
)


_REDUCEDDATA_DEVICEDATA = _descriptor.Descriptor(
  name='DeviceData',
  full_name='ghost.ReducedData.DeviceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ghost.ReducedData.DeviceData.value', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=578,
)

_REDUCEDDATA = _descriptor.Descriptor(
  name='ReducedData',
  full_name='ghost.ReducedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_data', full_name='ghost.ReducedData.device_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REDUCEDDATA_DEVICEDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=578,
)

_CR_CE_DEVICES_IP_DEVICES.containing_type = _CR_CE_DEVICES
_CR_CE_DEVICES_BLUETOOTH_DEVICES.containing_type = _CR_CE_DEVICES
_CR_CE_DEVICES_ZWAVE_DEVICES.containing_type = _CR_CE_DEVICES
_CR_CE_DEVICES_RF869_DEVICES.containing_type = _CR_CE_DEVICES
_CR_CE_DEVICES_ZIGBEE_DEVICES.containing_type = _CR_CE_DEVICES
_CR_CE_DEVICES.fields_by_name['ip_devices'].message_type = _CR_CE_DEVICES_IP_DEVICES
_CR_CE_DEVICES.fields_by_name['bt_devices'].message_type = _CR_CE_DEVICES_BLUETOOTH_DEVICES
_CR_CE_DEVICES.fields_by_name['zw_devices'].message_type = _CR_CE_DEVICES_ZWAVE_DEVICES
_CR_CE_DEVICES.fields_by_name['rf_devices'].message_type = _CR_CE_DEVICES_RF869_DEVICES
_CR_CE_DEVICES.fields_by_name['zb_devices'].message_type = _CR_CE_DEVICES_ZIGBEE_DEVICES
_REDUCEDDATA_DEVICEDATA.containing_type = _REDUCEDDATA
_REDUCEDDATA.fields_by_name['device_data'].message_type = _REDUCEDDATA_DEVICEDATA
DESCRIPTOR.message_types_by_name['CR_CE_Devices'] = _CR_CE_DEVICES
DESCRIPTOR.message_types_by_name['ReducedData'] = _REDUCEDDATA

CR_CE_Devices = _reflection.GeneratedProtocolMessageType('CR_CE_Devices', (_message.Message,), dict(

  IP_Devices = _reflection.GeneratedProtocolMessageType('IP_Devices', (_message.Message,), dict(
    DESCRIPTOR = _CR_CE_DEVICES_IP_DEVICES,
    __module__ = 'ghost_protocol.cr_ce_pb2'
    # @@protoc_insertion_point(class_scope:ghost.CR_CE_Devices.IP_Devices)
    ))
  ,

  Bluetooth_Devices = _reflection.GeneratedProtocolMessageType('Bluetooth_Devices', (_message.Message,), dict(
    DESCRIPTOR = _CR_CE_DEVICES_BLUETOOTH_DEVICES,
    __module__ = 'ghost_protocol.cr_ce_pb2'
    # @@protoc_insertion_point(class_scope:ghost.CR_CE_Devices.Bluetooth_Devices)
    ))
  ,

  ZWave_Devices = _reflection.GeneratedProtocolMessageType('ZWave_Devices', (_message.Message,), dict(
    DESCRIPTOR = _CR_CE_DEVICES_ZWAVE_DEVICES,
    __module__ = 'ghost_protocol.cr_ce_pb2'
    # @@protoc_insertion_point(class_scope:ghost.CR_CE_Devices.ZWave_Devices)
    ))
  ,

  RF869_Devices = _reflection.GeneratedProtocolMessageType('RF869_Devices', (_message.Message,), dict(
    DESCRIPTOR = _CR_CE_DEVICES_RF869_DEVICES,
    __module__ = 'ghost_protocol.cr_ce_pb2'
    # @@protoc_insertion_point(class_scope:ghost.CR_CE_Devices.RF869_Devices)
    ))
  ,

  Zigbee_Devices = _reflection.GeneratedProtocolMessageType('Zigbee_Devices', (_message.Message,), dict(
    DESCRIPTOR = _CR_CE_DEVICES_ZIGBEE_DEVICES,
    __module__ = 'ghost_protocol.cr_ce_pb2'
    # @@protoc_insertion_point(class_scope:ghost.CR_CE_Devices.Zigbee_Devices)
    ))
  ,
  DESCRIPTOR = _CR_CE_DEVICES,
  __module__ = 'ghost_protocol.cr_ce_pb2'
  # @@protoc_insertion_point(class_scope:ghost.CR_CE_Devices)
  ))
_sym_db.RegisterMessage(CR_CE_Devices)
_sym_db.RegisterMessage(CR_CE_Devices.IP_Devices)
_sym_db.RegisterMessage(CR_CE_Devices.Bluetooth_Devices)
_sym_db.RegisterMessage(CR_CE_Devices.ZWave_Devices)
_sym_db.RegisterMessage(CR_CE_Devices.RF869_Devices)
_sym_db.RegisterMessage(CR_CE_Devices.Zigbee_Devices)

ReducedData = _reflection.GeneratedProtocolMessageType('ReducedData', (_message.Message,), dict(

  DeviceData = _reflection.GeneratedProtocolMessageType('DeviceData', (_message.Message,), dict(
    DESCRIPTOR = _REDUCEDDATA_DEVICEDATA,
    __module__ = 'ghost_protocol.cr_ce_pb2'
    # @@protoc_insertion_point(class_scope:ghost.ReducedData.DeviceData)
    ))
  ,
  DESCRIPTOR = _REDUCEDDATA,
  __module__ = 'ghost_protocol.cr_ce_pb2'
  # @@protoc_insertion_point(class_scope:ghost.ReducedData)
  ))
_sym_db.RegisterMessage(ReducedData)
_sym_db.RegisterMessage(ReducedData.DeviceData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032eu.ghost_iot.communication'))
# @@protoc_insertion_point(module_scope)
