# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/cr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ghost_protocol import inter_pb2 as ghost__protocol_dot_inter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/cr.proto',
  package='ghost',
  syntax='proto2',
  serialized_pb=_b('\n\x17ghost_protocol/cr.proto\x12\x05ghost\x1a\x1aghost_protocol/inter.proto\"|\n\x06Metric\x12\x0f\n\x07id_slot\x18\x01 \x02(\x05\x12!\n\x05if_id\x18\x02 \x02(\x0b\x32\x12.ghost.InterfaceId\x12\x13\n\x0bmetric_name\x18\x03 \x02(\t\x12\x13\n\x0bmetric_type\x18\x04 \x02(\x05\x12\x14\n\x0cmetric_value\x18\x05 \x02(\x02\"s\n\x0c\x42\x61tteryLevel\x12\x0c\n\x04time\x18\x01 \x02(\x01\x12!\n\x05if_id\x18\x02 \x02(\x0b\x32\x12.ghost.InterfaceId\x12\x1f\n\x06\x64\x65v_id\x18\x03 \x02(\x0b\x32\x0f.ghost.DeviceId\x12\x11\n\tvariation\x18\x04 \x02(\x02\x42\x1c\n\x1a\x65u.ghost_iot.communication')
  ,
  dependencies=[ghost__protocol_dot_inter__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_METRIC = _descriptor.Descriptor(
  name='Metric',
  full_name='ghost.Metric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_slot', full_name='ghost.Metric.id_slot', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='if_id', full_name='ghost.Metric.if_id', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metric_name', full_name='ghost.Metric.metric_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metric_type', full_name='ghost.Metric.metric_type', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metric_value', full_name='ghost.Metric.metric_value', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=186,
)


_BATTERYLEVEL = _descriptor.Descriptor(
  name='BatteryLevel',
  full_name='ghost.BatteryLevel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='ghost.BatteryLevel.time', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='if_id', full_name='ghost.BatteryLevel.if_id', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dev_id', full_name='ghost.BatteryLevel.dev_id', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='variation', full_name='ghost.BatteryLevel.variation', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=303,
)

_METRIC.fields_by_name['if_id'].message_type = ghost__protocol_dot_inter__pb2._INTERFACEID
_BATTERYLEVEL.fields_by_name['if_id'].message_type = ghost__protocol_dot_inter__pb2._INTERFACEID
_BATTERYLEVEL.fields_by_name['dev_id'].message_type = ghost__protocol_dot_inter__pb2._DEVICEID
DESCRIPTOR.message_types_by_name['Metric'] = _METRIC
DESCRIPTOR.message_types_by_name['BatteryLevel'] = _BATTERYLEVEL

Metric = _reflection.GeneratedProtocolMessageType('Metric', (_message.Message,), dict(
  DESCRIPTOR = _METRIC,
  __module__ = 'ghost_protocol.cr_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Metric)
  ))
_sym_db.RegisterMessage(Metric)

BatteryLevel = _reflection.GeneratedProtocolMessageType('BatteryLevel', (_message.Message,), dict(
  DESCRIPTOR = _BATTERYLEVEL,
  __module__ = 'ghost_protocol.cr_pb2'
  # @@protoc_insertion_point(class_scope:ghost.BatteryLevel)
  ))
_sym_db.RegisterMessage(BatteryLevel)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032eu.ghost_iot.communication'))
# @@protoc_insertion_point(module_scope)
