# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/ndfa.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ghost_protocol import inter_pb2 as ghost__protocol_dot_inter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/ndfa.proto',
  package='ghost',
  syntax='proto2',
  serialized_pb=_b('\n\x19ghost_protocol/ndfa.proto\x12\x05ghost\x1a\x1aghost_protocol/inter.proto\"\x9c\x01\n\x0e\x46ileProcessing\x12\x33\n\nalert_type\x18\x01 \x02(\x0e\x32\x1f.ghost.FileProcessing.AlertType\x12!\n\x05if_id\x18\x02 \x02(\x0b\x32\x12.ghost.InterfaceId\x12\x11\n\tfile_name\x18\x03 \x02(\t\"\x1f\n\tAlertType\x12\t\n\x05\x42\x45GIN\x10\x00\x12\x07\n\x03\x45ND\x10\x01\"\xe1\x01\n\tFlowAdded\x12!\n\x05if_id\x18\x01 \x02(\x0b\x32\x12.ghost.InterfaceId\x12\x0f\n\x07\x66low_id\x18\x02 \x02(\x05\x12\x13\n\x0bsrc_address\x18\x03 \x02(\t\x12\x13\n\x0b\x64st_address\x18\x04 \x02(\t\x12\x15\n\rtotal_bytes_a\x18\x05 \x02(\x05\x12\x11\n\tpackets_a\x18\x06 \x02(\x05\x12\x15\n\rtotal_bytes_b\x18\x07 \x02(\x05\x12\x11\n\tpackets_b\x18\x08 \x02(\x05\x12\"\n\x04type\x18\t \x02(\x0e\x32\x14.ghost.InterfaceTypeB\x1c\n\x1a\x65u.ghost_iot.communication')
  ,
  dependencies=[ghost__protocol_dot_inter__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_FILEPROCESSING_ALERTTYPE = _descriptor.EnumDescriptor(
  name='AlertType',
  full_name='ghost.FileProcessing.AlertType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BEGIN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='END', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=190,
  serialized_end=221,
)
_sym_db.RegisterEnumDescriptor(_FILEPROCESSING_ALERTTYPE)


_FILEPROCESSING = _descriptor.Descriptor(
  name='FileProcessing',
  full_name='ghost.FileProcessing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alert_type', full_name='ghost.FileProcessing.alert_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='if_id', full_name='ghost.FileProcessing.if_id', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='ghost.FileProcessing.file_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FILEPROCESSING_ALERTTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=221,
)


_FLOWADDED = _descriptor.Descriptor(
  name='FlowAdded',
  full_name='ghost.FlowAdded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='if_id', full_name='ghost.FlowAdded.if_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flow_id', full_name='ghost.FlowAdded.flow_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='src_address', full_name='ghost.FlowAdded.src_address', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dst_address', full_name='ghost.FlowAdded.dst_address', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_bytes_a', full_name='ghost.FlowAdded.total_bytes_a', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='packets_a', full_name='ghost.FlowAdded.packets_a', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_bytes_b', full_name='ghost.FlowAdded.total_bytes_b', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='packets_b', full_name='ghost.FlowAdded.packets_b', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='ghost.FlowAdded.type', index=8,
      number=9, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=449,
)

_FILEPROCESSING.fields_by_name['alert_type'].enum_type = _FILEPROCESSING_ALERTTYPE
_FILEPROCESSING.fields_by_name['if_id'].message_type = ghost__protocol_dot_inter__pb2._INTERFACEID
_FILEPROCESSING_ALERTTYPE.containing_type = _FILEPROCESSING
_FLOWADDED.fields_by_name['if_id'].message_type = ghost__protocol_dot_inter__pb2._INTERFACEID
_FLOWADDED.fields_by_name['type'].enum_type = ghost__protocol_dot_inter__pb2._INTERFACETYPE
DESCRIPTOR.message_types_by_name['FileProcessing'] = _FILEPROCESSING
DESCRIPTOR.message_types_by_name['FlowAdded'] = _FLOWADDED

FileProcessing = _reflection.GeneratedProtocolMessageType('FileProcessing', (_message.Message,), dict(
  DESCRIPTOR = _FILEPROCESSING,
  __module__ = 'ghost_protocol.ndfa_pb2'
  # @@protoc_insertion_point(class_scope:ghost.FileProcessing)
  ))
_sym_db.RegisterMessage(FileProcessing)

FlowAdded = _reflection.GeneratedProtocolMessageType('FlowAdded', (_message.Message,), dict(
  DESCRIPTOR = _FLOWADDED,
  __module__ = 'ghost_protocol.ndfa_pb2'
  # @@protoc_insertion_point(class_scope:ghost.FlowAdded)
  ))
_sym_db.RegisterMessage(FlowAdded)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032eu.ghost_iot.communication'))
# @@protoc_insertion_point(module_scope)
