# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/pb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/pb.proto',
  package='ghost',
  syntax='proto2',
  serialized_pb=_b('\n\x17ghost_protocol/pb.proto\x12\x05ghost\"\xbd\x01\n\tBluetooth\x12\x10\n\x08\x62\x61tch_id\x18\x01 \x01(\t\x12\x19\n\x11number_of_packets\x18\x02 \x01(\r\x12\x10\n\x08taxonomy\x18\x03 \x01(\t\x12\x12\n\nstart_time\x18\x04 \x01(\r\x12\x10\n\x08min_size\x18\x05 \x01(\r\x12\x10\n\x08\x64uration\x18\x06 \x01(\r\x12\x11\n\tstop_time\x18\x07 \x01(\r\x12\x10\n\x08max_size\x18\x08 \x01(\r\x12\x14\n\x0c\x61verage_size\x18\t \x01(\r\"k\n\x1eSafetyRefinementReplyBluetooth\x12\x15\n\rgraphAccepted\x18\x01 \x02(\x08\x12\x11\n\tgraphType\x18\x02 \x02(\r\x12\x1f\n\x05graph\x18\x03 \x03(\x0b\x32\x10.ghost.BluetoothB\x1c\n\x1a\x65u.ghost_iot.communication')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BLUETOOTH = _descriptor.Descriptor(
  name='Bluetooth',
  full_name='ghost.Bluetooth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='batch_id', full_name='ghost.Bluetooth.batch_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number_of_packets', full_name='ghost.Bluetooth.number_of_packets', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='taxonomy', full_name='ghost.Bluetooth.taxonomy', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='ghost.Bluetooth.start_time', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_size', full_name='ghost.Bluetooth.min_size', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='ghost.Bluetooth.duration', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stop_time', full_name='ghost.Bluetooth.stop_time', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_size', full_name='ghost.Bluetooth.max_size', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='average_size', full_name='ghost.Bluetooth.average_size', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=224,
)


_SAFETYREFINEMENTREPLYBLUETOOTH = _descriptor.Descriptor(
  name='SafetyRefinementReplyBluetooth',
  full_name='ghost.SafetyRefinementReplyBluetooth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='graphAccepted', full_name='ghost.SafetyRefinementReplyBluetooth.graphAccepted', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='graphType', full_name='ghost.SafetyRefinementReplyBluetooth.graphType', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='graph', full_name='ghost.SafetyRefinementReplyBluetooth.graph', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=333,
)

_SAFETYREFINEMENTREPLYBLUETOOTH.fields_by_name['graph'].message_type = _BLUETOOTH
DESCRIPTOR.message_types_by_name['Bluetooth'] = _BLUETOOTH
DESCRIPTOR.message_types_by_name['SafetyRefinementReplyBluetooth'] = _SAFETYREFINEMENTREPLYBLUETOOTH

Bluetooth = _reflection.GeneratedProtocolMessageType('Bluetooth', (_message.Message,), dict(
  DESCRIPTOR = _BLUETOOTH,
  __module__ = 'ghost_protocol.pb_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Bluetooth)
  ))
_sym_db.RegisterMessage(Bluetooth)

SafetyRefinementReplyBluetooth = _reflection.GeneratedProtocolMessageType('SafetyRefinementReplyBluetooth', (_message.Message,), dict(
  DESCRIPTOR = _SAFETYREFINEMENTREPLYBLUETOOTH,
  __module__ = 'ghost_protocol.pb_pb2'
  # @@protoc_insertion_point(class_scope:ghost.SafetyRefinementReplyBluetooth)
  ))
_sym_db.RegisterMessage(SafetyRefinementReplyBluetooth)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032eu.ghost_iot.communication'))
# @@protoc_insertion_point(module_scope)
