# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/sc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/sc.proto',
  package='ghost',
  syntax='proto2',
  serialized_pb=_b('\n\x17ghost_protocol/sc.proto\x12\x05ghost\"\x10\n\x02Ip\x12\n\n\x02ip\x18\x01 \x02(\t\"\x1a\n\x0cReport_ip_ok\x12\n\n\x02ok\x18\x01 \x02(\x08\"\x19\n\x08Ip_score\x12\r\n\x05score\x18\x01 \x02(\x01\"#\n\x07Ip_list\x12\n\n\x02ip\x18\x01 \x02(\t\x12\x0c\n\x04list\x18\x02 \x02(\x08\"/\n\x0bIp_presence\x12\x0e\n\x06status\x18\x01 \x02(\x08\x12\x10\n\x08presence\x18\x02 \x02(\x08\"0\n\tintegrity\x12\x10\n\x08response\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x02(\t\"\x16\n\x06method\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\tB\x1c\n\x1a\x65u.ghost_iot.communication')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IP = _descriptor.Descriptor(
  name='Ip',
  full_name='ghost.Ip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='ghost.Ip.ip', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=50,
)


_REPORT_IP_OK = _descriptor.Descriptor(
  name='Report_ip_ok',
  full_name='ghost.Report_ip_ok',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='ghost.Report_ip_ok.ok', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=78,
)


_IP_SCORE = _descriptor.Descriptor(
  name='Ip_score',
  full_name='ghost.Ip_score',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='ghost.Ip_score.score', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=105,
)


_IP_LIST = _descriptor.Descriptor(
  name='Ip_list',
  full_name='ghost.Ip_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='ghost.Ip_list.ip', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='list', full_name='ghost.Ip_list.list', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=142,
)


_IP_PRESENCE = _descriptor.Descriptor(
  name='Ip_presence',
  full_name='ghost.Ip_presence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ghost.Ip_presence.status', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='presence', full_name='ghost.Ip_presence.presence', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=191,
)


_INTEGRITY = _descriptor.Descriptor(
  name='integrity',
  full_name='ghost.integrity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='ghost.integrity.response', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ghost.integrity.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=241,
)


_METHOD = _descriptor.Descriptor(
  name='method',
  full_name='ghost.method',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ghost.method.data', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=265,
)

DESCRIPTOR.message_types_by_name['Ip'] = _IP
DESCRIPTOR.message_types_by_name['Report_ip_ok'] = _REPORT_IP_OK
DESCRIPTOR.message_types_by_name['Ip_score'] = _IP_SCORE
DESCRIPTOR.message_types_by_name['Ip_list'] = _IP_LIST
DESCRIPTOR.message_types_by_name['Ip_presence'] = _IP_PRESENCE
DESCRIPTOR.message_types_by_name['integrity'] = _INTEGRITY
DESCRIPTOR.message_types_by_name['method'] = _METHOD

Ip = _reflection.GeneratedProtocolMessageType('Ip', (_message.Message,), dict(
  DESCRIPTOR = _IP,
  __module__ = 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Ip)
  ))
_sym_db.RegisterMessage(Ip)

Report_ip_ok = _reflection.GeneratedProtocolMessageType('Report_ip_ok', (_message.Message,), dict(
  DESCRIPTOR = _REPORT_IP_OK,
  __module__ = 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Report_ip_ok)
  ))
_sym_db.RegisterMessage(Report_ip_ok)

Ip_score = _reflection.GeneratedProtocolMessageType('Ip_score', (_message.Message,), dict(
  DESCRIPTOR = _IP_SCORE,
  __module__ = 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Ip_score)
  ))
_sym_db.RegisterMessage(Ip_score)

Ip_list = _reflection.GeneratedProtocolMessageType('Ip_list', (_message.Message,), dict(
  DESCRIPTOR = _IP_LIST,
  __module__ = 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Ip_list)
  ))
_sym_db.RegisterMessage(Ip_list)

Ip_presence = _reflection.GeneratedProtocolMessageType('Ip_presence', (_message.Message,), dict(
  DESCRIPTOR = _IP_PRESENCE,
  __module__ = 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Ip_presence)
  ))
_sym_db.RegisterMessage(Ip_presence)

integrity = _reflection.GeneratedProtocolMessageType('integrity', (_message.Message,), dict(
  DESCRIPTOR = _INTEGRITY,
  __module__ = 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.integrity)
  ))
_sym_db.RegisterMessage(integrity)

method = _reflection.GeneratedProtocolMessageType('method', (_message.Message,), dict(
  DESCRIPTOR = _METHOD,
  __module__ = 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.method)
  ))
_sym_db.RegisterMessage(method)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032eu.ghost_iot.communication'))
# @@protoc_insertion_point(module_scope)
