# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/sds.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/sds.proto',
  package='ghost',
  syntax='proto2',
  serialized_pb=_b('\n\x18ghost_protocol/sds.proto\x12\x05ghost\",\n\rPreDeleteData\x12\x0c\n\x04\x64\x61te\x18\x01 \x02(\t\x12\r\n\x05table\x18\x02 \x02(\t\"(\n\nDeleteData\x12\x0c\n\x04\x64\x61te\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\"/\n\x05Ready\x12&\n\x0bready_state\x18\x01 \x02(\x0e\x32\x11.ghost.ReadyState*%\n\nReadyState\x12\x0c\n\x08NOTREADY\x10\x01\x12\t\n\x05READY\x10\x02\x42\x1c\n\x1a\x65u.ghost_iot.communication')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_READYSTATE = _descriptor.EnumDescriptor(
  name='ReadyState',
  full_name='ghost.ReadyState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOTREADY', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READY', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=172,
  serialized_end=209,
)
_sym_db.RegisterEnumDescriptor(_READYSTATE)

ReadyState = enum_type_wrapper.EnumTypeWrapper(_READYSTATE)
NOTREADY = 1
READY = 2



_PREDELETEDATA = _descriptor.Descriptor(
  name='PreDeleteData',
  full_name='ghost.PreDeleteData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='ghost.PreDeleteData.date', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='table', full_name='ghost.PreDeleteData.table', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=79,
)


_DELETEDATA = _descriptor.Descriptor(
  name='DeleteData',
  full_name='ghost.DeleteData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='ghost.DeleteData.date', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='ghost.DeleteData.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=121,
)


_READY = _descriptor.Descriptor(
  name='Ready',
  full_name='ghost.Ready',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ready_state', full_name='ghost.Ready.ready_state', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=170,
)

_READY.fields_by_name['ready_state'].enum_type = _READYSTATE
DESCRIPTOR.message_types_by_name['PreDeleteData'] = _PREDELETEDATA
DESCRIPTOR.message_types_by_name['DeleteData'] = _DELETEDATA
DESCRIPTOR.message_types_by_name['Ready'] = _READY
DESCRIPTOR.enum_types_by_name['ReadyState'] = _READYSTATE

PreDeleteData = _reflection.GeneratedProtocolMessageType('PreDeleteData', (_message.Message,), dict(
  DESCRIPTOR = _PREDELETEDATA,
  __module__ = 'ghost_protocol.sds_pb2'
  # @@protoc_insertion_point(class_scope:ghost.PreDeleteData)
  ))
_sym_db.RegisterMessage(PreDeleteData)

DeleteData = _reflection.GeneratedProtocolMessageType('DeleteData', (_message.Message,), dict(
  DESCRIPTOR = _DELETEDATA,
  __module__ = 'ghost_protocol.sds_pb2'
  # @@protoc_insertion_point(class_scope:ghost.DeleteData)
  ))
_sym_db.RegisterMessage(DeleteData)

Ready = _reflection.GeneratedProtocolMessageType('Ready', (_message.Message,), dict(
  DESCRIPTOR = _READY,
  __module__ = 'ghost_protocol.sds_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Ready)
  ))
_sym_db.RegisterMessage(Ready)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032eu.ghost_iot.communication'))
# @@protoc_insertion_point(module_scope)
