# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/spr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ghost_protocol import risk_engine_pb2 as ghost__protocol_dot_risk__engine__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/spr.proto',
  package='ghost',
  syntax='proto2',
  serialized_pb=_b('\n\x18ghost_protocol/spr.proto\x12\x05ghost\x1a ghost_protocol/risk_engine.proto\"\xc8\x01\n\tIPTHREATS\x12\n\n\x02IP\x18\x01 \x02(\t\x12(\n\x07Threats\x18\x02 \x03(\x0b\x32\x17.ghost.IPTHREATS.THREAT\x1a\x84\x01\n\x06THREAT\x12\x19\n\x11\x61ttackDescription\x18\x01 \x02(\t\x12\x12\n\nattackType\x18\x02 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x02(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x02(\t\x12\x0e\n\x06\x64omain\x18\x05 \x02(\t\x12\x0e\n\x06source\x18\x06 \x02(\t\x12\x0c\n\x04time\x18\x07 \x02(\t\"<\n\x0bSGraphsIpV4\x12-\n\x07profile\x18\x01 \x03(\x0b\x32\x1c.ghost.IpV4ProfileAcceptance\"F\n\x10SGraphsBluetooth\x12\x32\n\x07profile\x18\x01 \x03(\x0b\x32!.ghost.BluetoothProfileAcceptance\">\n\x0cSGraphsZwave\x12.\n\x07profile\x18\x01 \x03(\x0b\x32\x1d.ghost.ZWaveProfileAcceptanceB\x1c\n\x1a\x65u.ghost_iot.communication')
  ,
  dependencies=[ghost__protocol_dot_risk__engine__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IPTHREATS_THREAT = _descriptor.Descriptor(
  name='THREAT',
  full_name='ghost.IPTHREATS.THREAT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attackDescription', full_name='ghost.IPTHREATS.THREAT.attackDescription', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attackType', full_name='ghost.IPTHREATS.THREAT.attackType', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='ghost.IPTHREATS.THREAT.country', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='date', full_name='ghost.IPTHREATS.THREAT.date', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='domain', full_name='ghost.IPTHREATS.THREAT.domain', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='ghost.IPTHREATS.THREAT.source', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time', full_name='ghost.IPTHREATS.THREAT.time', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=270,
)

_IPTHREATS = _descriptor.Descriptor(
  name='IPTHREATS',
  full_name='ghost.IPTHREATS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IP', full_name='ghost.IPTHREATS.IP', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Threats', full_name='ghost.IPTHREATS.Threats', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_IPTHREATS_THREAT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=270,
)


_SGRAPHSIPV4 = _descriptor.Descriptor(
  name='SGraphsIpV4',
  full_name='ghost.SGraphsIpV4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile', full_name='ghost.SGraphsIpV4.profile', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=332,
)


_SGRAPHSBLUETOOTH = _descriptor.Descriptor(
  name='SGraphsBluetooth',
  full_name='ghost.SGraphsBluetooth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile', full_name='ghost.SGraphsBluetooth.profile', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=404,
)


_SGRAPHSZWAVE = _descriptor.Descriptor(
  name='SGraphsZwave',
  full_name='ghost.SGraphsZwave',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='profile', full_name='ghost.SGraphsZwave.profile', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=468,
)

_IPTHREATS_THREAT.containing_type = _IPTHREATS
_IPTHREATS.fields_by_name['Threats'].message_type = _IPTHREATS_THREAT
_SGRAPHSIPV4.fields_by_name['profile'].message_type = ghost__protocol_dot_risk__engine__pb2._IPV4PROFILEACCEPTANCE
_SGRAPHSBLUETOOTH.fields_by_name['profile'].message_type = ghost__protocol_dot_risk__engine__pb2._BLUETOOTHPROFILEACCEPTANCE
_SGRAPHSZWAVE.fields_by_name['profile'].message_type = ghost__protocol_dot_risk__engine__pb2._ZWAVEPROFILEACCEPTANCE
DESCRIPTOR.message_types_by_name['IPTHREATS'] = _IPTHREATS
DESCRIPTOR.message_types_by_name['SGraphsIpV4'] = _SGRAPHSIPV4
DESCRIPTOR.message_types_by_name['SGraphsBluetooth'] = _SGRAPHSBLUETOOTH
DESCRIPTOR.message_types_by_name['SGraphsZwave'] = _SGRAPHSZWAVE

IPTHREATS = _reflection.GeneratedProtocolMessageType('IPTHREATS', (_message.Message,), dict(

  THREAT = _reflection.GeneratedProtocolMessageType('THREAT', (_message.Message,), dict(
    DESCRIPTOR = _IPTHREATS_THREAT,
    __module__ = 'ghost_protocol.spr_pb2'
    # @@protoc_insertion_point(class_scope:ghost.IPTHREATS.THREAT)
    ))
  ,
  DESCRIPTOR = _IPTHREATS,
  __module__ = 'ghost_protocol.spr_pb2'
  # @@protoc_insertion_point(class_scope:ghost.IPTHREATS)
  ))
_sym_db.RegisterMessage(IPTHREATS)
_sym_db.RegisterMessage(IPTHREATS.THREAT)

SGraphsIpV4 = _reflection.GeneratedProtocolMessageType('SGraphsIpV4', (_message.Message,), dict(
  DESCRIPTOR = _SGRAPHSIPV4,
  __module__ = 'ghost_protocol.spr_pb2'
  # @@protoc_insertion_point(class_scope:ghost.SGraphsIpV4)
  ))
_sym_db.RegisterMessage(SGraphsIpV4)

SGraphsBluetooth = _reflection.GeneratedProtocolMessageType('SGraphsBluetooth', (_message.Message,), dict(
  DESCRIPTOR = _SGRAPHSBLUETOOTH,
  __module__ = 'ghost_protocol.spr_pb2'
  # @@protoc_insertion_point(class_scope:ghost.SGraphsBluetooth)
  ))
_sym_db.RegisterMessage(SGraphsBluetooth)

SGraphsZwave = _reflection.GeneratedProtocolMessageType('SGraphsZwave', (_message.Message,), dict(
  DESCRIPTOR = _SGRAPHSZWAVE,
  __module__ = 'ghost_protocol.spr_pb2'
  # @@protoc_insertion_point(class_scope:ghost.SGraphsZwave)
  ))
_sym_db.RegisterMessage(SGraphsZwave)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032eu.ghost_iot.communication'))
# @@protoc_insertion_point(module_scope)
