# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/te_cs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ghost_protocol import inter_pb2 as ghost__protocol_dot_inter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/te_cs.proto',
  package='ghost',
  syntax='proto2',
  serialized_pb=_b('\n\x1aghost_protocol/te_cs.proto\x12\x05ghost\x1a\x1aghost_protocol/inter.proto\"\xd4\x06\n\x13\x43ybersecurityStatus\x12%\n\x07if_type\x18\x01 \x02(\x0e\x32\x14.ghost.InterfaceType\x12!\n\x05if_id\x18\x02 \x02(\x0b\x32\x12.ghost.InterfaceId\x12\x0f\n\x07id_slot\x18\x03 \x02(\x05\x12\x14\n\x0c\x61ttack_proba\x18\x04 \x02(\x02\x12\x12\n\nstart_time\x18\x05 \x02(\x01\x12\x10\n\x08\x65nd_time\x18\x06 \x02(\x01\x12N\n\x15\x61ttack_classification\x18\x07 \x03(\x0b\x32/.ghost.CybersecurityStatus.AttackClassification\x1a\x93\x01\n\x14\x41ttackClassification\x12\x42\n\x0c\x61ttack_class\x18\x01 \x02(\x0e\x32,.ghost.CybersecurityStatus.AttackAttribution\x12\x13\n\x0bprobability\x18\x02 \x02(\x02\x12\"\n\tdevice_id\x18\x03 \x01(\x0b\x32\x0f.ghost.DeviceId\"\xbf\x03\n\x11\x41ttackAttribution\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x11\n\rTCP_SYN_FLOOD\x10\x01\x12\x12\n\x0eTCP_SYN_SILENT\x10\x02\x12\r\n\tUDP_FLOOD\x10\x03\x12\x0e\n\nUDP_SILENT\x10\x04\x12\x0e\n\nICMP_FLOOD\x10\x05\x12\x0f\n\x0bICMP_SILENT\x10\x06\x12\x12\n\x0e\x42\x41TTERY_ATTACK\x10\x07\x12\x12\n\x0e\x42\x41TTERY_SILENT\x10\x08\x12\r\n\tPKT_FLOOD\x10\t\x12\x0e\n\nPKT_SILENT\x10\n\x12\x12\n\x0ePKT_SIZE_LARGE\x10\x0b\x12\x12\n\x0ePKT_SIZE_SMALL\x10\x0c\x12\x14\n\x10THROUGHPUT_FLOOD\x10\r\x12\x15\n\x11THROUGHPUT_SILENT\x10\x0e\x12\x17\n\x13INTER_PKT_TIME_SLOW\x10\x0f\x12\x17\n\x13INTER_PKT_TIME_FAST\x10\x10\x12\x17\n\x13THROUGHPUT_TO_FLOOD\x10\x11\x12\x18\n\x14THROUGHPUT_TO_SILENT\x10\x12\x12\x19\n\x15THROUGHPUT_FROM_FLOOD\x10\x13\x12\x1a\n\x16THROUGHPUT_FROM_SILENT\x10\x14\x42\x1c\n\x1a\x65u.ghost_iot.communication')
  ,
  dependencies=[ghost__protocol_dot_inter__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CYBERSECURITYSTATUS_ATTACKATTRIBUTION = _descriptor.EnumDescriptor(
  name='AttackAttribution',
  full_name='ghost.CybersecurityStatus.AttackAttribution',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TCP_SYN_FLOOD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TCP_SYN_SILENT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UDP_FLOOD', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UDP_SILENT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ICMP_FLOOD', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ICMP_SILENT', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BATTERY_ATTACK', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BATTERY_SILENT', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PKT_FLOOD', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PKT_SILENT', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PKT_SIZE_LARGE', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PKT_SIZE_SMALL', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THROUGHPUT_FLOOD', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THROUGHPUT_SILENT', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTER_PKT_TIME_SLOW', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTER_PKT_TIME_FAST', index=16, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THROUGHPUT_TO_FLOOD', index=17, number=17,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THROUGHPUT_TO_SILENT', index=18, number=18,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THROUGHPUT_FROM_FLOOD', index=19, number=19,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THROUGHPUT_FROM_SILENT', index=20, number=20,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=471,
  serialized_end=918,
)
_sym_db.RegisterEnumDescriptor(_CYBERSECURITYSTATUS_ATTACKATTRIBUTION)


_CYBERSECURITYSTATUS_ATTACKCLASSIFICATION = _descriptor.Descriptor(
  name='AttackClassification',
  full_name='ghost.CybersecurityStatus.AttackClassification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attack_class', full_name='ghost.CybersecurityStatus.AttackClassification.attack_class', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='probability', full_name='ghost.CybersecurityStatus.AttackClassification.probability', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='ghost.CybersecurityStatus.AttackClassification.device_id', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=468,
)

_CYBERSECURITYSTATUS = _descriptor.Descriptor(
  name='CybersecurityStatus',
  full_name='ghost.CybersecurityStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='if_type', full_name='ghost.CybersecurityStatus.if_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='if_id', full_name='ghost.CybersecurityStatus.if_id', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id_slot', full_name='ghost.CybersecurityStatus.id_slot', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack_proba', full_name='ghost.CybersecurityStatus.attack_proba', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='ghost.CybersecurityStatus.start_time', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='ghost.CybersecurityStatus.end_time', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack_classification', full_name='ghost.CybersecurityStatus.attack_classification', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CYBERSECURITYSTATUS_ATTACKCLASSIFICATION, ],
  enum_types=[
    _CYBERSECURITYSTATUS_ATTACKATTRIBUTION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=918,
)

_CYBERSECURITYSTATUS_ATTACKCLASSIFICATION.fields_by_name['attack_class'].enum_type = _CYBERSECURITYSTATUS_ATTACKATTRIBUTION
_CYBERSECURITYSTATUS_ATTACKCLASSIFICATION.fields_by_name['device_id'].message_type = ghost__protocol_dot_inter__pb2._DEVICEID
_CYBERSECURITYSTATUS_ATTACKCLASSIFICATION.containing_type = _CYBERSECURITYSTATUS
_CYBERSECURITYSTATUS.fields_by_name['if_type'].enum_type = ghost__protocol_dot_inter__pb2._INTERFACETYPE
_CYBERSECURITYSTATUS.fields_by_name['if_id'].message_type = ghost__protocol_dot_inter__pb2._INTERFACEID
_CYBERSECURITYSTATUS.fields_by_name['attack_classification'].message_type = _CYBERSECURITYSTATUS_ATTACKCLASSIFICATION
_CYBERSECURITYSTATUS_ATTACKATTRIBUTION.containing_type = _CYBERSECURITYSTATUS
DESCRIPTOR.message_types_by_name['CybersecurityStatus'] = _CYBERSECURITYSTATUS

CybersecurityStatus = _reflection.GeneratedProtocolMessageType('CybersecurityStatus', (_message.Message,), dict(

  AttackClassification = _reflection.GeneratedProtocolMessageType('AttackClassification', (_message.Message,), dict(
    DESCRIPTOR = _CYBERSECURITYSTATUS_ATTACKCLASSIFICATION,
    __module__ = 'ghost_protocol.te_cs_pb2'
    # @@protoc_insertion_point(class_scope:ghost.CybersecurityStatus.AttackClassification)
    ))
  ,
  DESCRIPTOR = _CYBERSECURITYSTATUS,
  __module__ = 'ghost_protocol.te_cs_pb2'
  # @@protoc_insertion_point(class_scope:ghost.CybersecurityStatus)
  ))
_sym_db.RegisterMessage(CybersecurityStatus)
_sym_db.RegisterMessage(CybersecurityStatus.AttackClassification)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032eu.ghost_iot.communication'))
# @@protoc_insertion_point(module_scope)
