# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/te_dc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ghost_protocol import inter_pb2 as ghost__protocol_dot_inter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/te_dc.proto',
  package='ghost',
  syntax='proto2',
  serialized_pb=_b('\n\x1aghost_protocol/te_dc.proto\x12\x05ghost\x1a\x1aghost_protocol/inter.proto\"W\n\x10\x41nomalyDetection\x12\r\n\x05score\x18\x01 \x02(\x01\x12!\n\x06\x64\x65vice\x18\x02 \x02(\x0b\x32\x11.ghost.DeviceInfo\x12\x11\n\ttimestamp\x18\x03 \x02(\tB\x1c\n\x1a\x65u.ghost_iot.communication')
  ,
  dependencies=[ghost__protocol_dot_inter__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ANOMALYDETECTION = _descriptor.Descriptor(
  name='AnomalyDetection',
  full_name='ghost.AnomalyDetection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='ghost.AnomalyDetection.score', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device', full_name='ghost.AnomalyDetection.device', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ghost.AnomalyDetection.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=152,
)

_ANOMALYDETECTION.fields_by_name['device'].message_type = ghost__protocol_dot_inter__pb2._DEVICEINFO
DESCRIPTOR.message_types_by_name['AnomalyDetection'] = _ANOMALYDETECTION

AnomalyDetection = _reflection.GeneratedProtocolMessageType('AnomalyDetection', (_message.Message,), dict(
  DESCRIPTOR = _ANOMALYDETECTION,
  __module__ = 'ghost_protocol.te_dc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.AnomalyDetection)
  ))
_sym_db.RegisterMessage(AnomalyDetection)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032eu.ghost_iot.communication'))
# @@protoc_insertion_point(module_scope)
