# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/cr_ce.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/cr_ce.proto',
  package='ghost',
  syntax='proto2',
  serialized_options=b'\n\032eu.ghost_iot.communication',
  serialized_pb=b'\n\x1aghost_protocol/cr_ce.proto\x12\x05ghost\"\xcf\x03\n\rCR_CE_Devices\x12\x33\n\nip_devices\x18\x01 \x01(\x0b\x32\x1f.ghost.CR_CE_Devices.IP_Devices\x12:\n\nbt_devices\x18\x02 \x01(\x0b\x32&.ghost.CR_CE_Devices.Bluetooth_Devices\x12\x36\n\nzw_devices\x18\x03 \x01(\x0b\x32\".ghost.CR_CE_Devices.ZWave_Devices\x12\x36\n\nrf_devices\x18\x04 \x01(\x0b\x32\".ghost.CR_CE_Devices.RF869_Devices\x12\x37\n\nzb_devices\x18\x05 \x01(\x0b\x32#.ghost.CR_CE_Devices.Zigbee_Devices\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x1a\x18\n\nIP_Devices\x12\n\n\x02ip\x18\x01 \x03(\t\x1a\x1f\n\x11\x42luetooth_Devices\x12\n\n\x02\x62t\x18\x01 \x03(\t\x1a\x1b\n\rZWave_Devices\x12\n\n\x02zw\x18\x01 \x03(\t\x1a\x1b\n\rRF869_Devices\x12\n\n\x02rf\x18\x01 \x03(\t\x1a\x1c\n\x0eZigbee_Devices\x12\n\n\x02zb\x18\x01 \x03(\t\"^\n\x0bReducedData\x12\x32\n\x0b\x64\x65vice_data\x18\x01 \x03(\x0b\x32\x1d.ghost.ReducedData.DeviceData\x1a\x1b\n\nDeviceData\x12\r\n\x05value\x18\x01 \x03(\x01\"\xd0\x01\n\x17\x44\x61taForContextReasoning\x12\x38\n\x08new_data\x18\x01 \x02(\x0b\x32&.ghost.DataForContextReasoning.NewData\x12\x42\n\rtemplate_data\x18\x02 \x02(\x0b\x32+.ghost.DataForContextReasoning.TemplateData\x1a\x18\n\x07NewData\x12\r\n\x05value\x18\x01 \x03(\x01\x1a\x1d\n\x0cTemplateData\x12\r\n\x05value\x18\x01 \x03(\x01\"_\n\x08\x46ullData\x12(\n\x0creduced_data\x18\x01 \x02(\x0b\x32\x12.ghost.ReducedData\x12)\n\rtraining_data\x18\x02 \x03(\x0b\x32\x12.ghost.ReducedDataB\x1c\n\x1a\x65u.ghost_iot.communication'
)




_CR_CE_DEVICES_IP_DEVICES = _descriptor.Descriptor(
  name='IP_Devices',
  full_name='ghost.CR_CE_Devices.IP_Devices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='ghost.CR_CE_Devices.IP_Devices.ip', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=380,
)

_CR_CE_DEVICES_BLUETOOTH_DEVICES = _descriptor.Descriptor(
  name='Bluetooth_Devices',
  full_name='ghost.CR_CE_Devices.Bluetooth_Devices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bt', full_name='ghost.CR_CE_Devices.Bluetooth_Devices.bt', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=413,
)

_CR_CE_DEVICES_ZWAVE_DEVICES = _descriptor.Descriptor(
  name='ZWave_Devices',
  full_name='ghost.CR_CE_Devices.ZWave_Devices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zw', full_name='ghost.CR_CE_Devices.ZWave_Devices.zw', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=442,
)

_CR_CE_DEVICES_RF869_DEVICES = _descriptor.Descriptor(
  name='RF869_Devices',
  full_name='ghost.CR_CE_Devices.RF869_Devices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rf', full_name='ghost.CR_CE_Devices.RF869_Devices.rf', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=471,
)

_CR_CE_DEVICES_ZIGBEE_DEVICES = _descriptor.Descriptor(
  name='Zigbee_Devices',
  full_name='ghost.CR_CE_Devices.Zigbee_Devices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='zb', full_name='ghost.CR_CE_Devices.Zigbee_Devices.zb', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=501,
)

_CR_CE_DEVICES = _descriptor.Descriptor(
  name='CR_CE_Devices',
  full_name='ghost.CR_CE_Devices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_devices', full_name='ghost.CR_CE_Devices.ip_devices', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bt_devices', full_name='ghost.CR_CE_Devices.bt_devices', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zw_devices', full_name='ghost.CR_CE_Devices.zw_devices', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rf_devices', full_name='ghost.CR_CE_Devices.rf_devices', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='zb_devices', full_name='ghost.CR_CE_Devices.zb_devices', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ghost.CR_CE_Devices.timestamp', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CR_CE_DEVICES_IP_DEVICES, _CR_CE_DEVICES_BLUETOOTH_DEVICES, _CR_CE_DEVICES_ZWAVE_DEVICES, _CR_CE_DEVICES_RF869_DEVICES, _CR_CE_DEVICES_ZIGBEE_DEVICES, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=501,
)


_REDUCEDDATA_DEVICEDATA = _descriptor.Descriptor(
  name='DeviceData',
  full_name='ghost.ReducedData.DeviceData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ghost.ReducedData.DeviceData.value', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=597,
)

_REDUCEDDATA = _descriptor.Descriptor(
  name='ReducedData',
  full_name='ghost.ReducedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_data', full_name='ghost.ReducedData.device_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_REDUCEDDATA_DEVICEDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=597,
)


_DATAFORCONTEXTREASONING_NEWDATA = _descriptor.Descriptor(
  name='NewData',
  full_name='ghost.DataForContextReasoning.NewData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ghost.DataForContextReasoning.NewData.value', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=753,
  serialized_end=777,
)

_DATAFORCONTEXTREASONING_TEMPLATEDATA = _descriptor.Descriptor(
  name='TemplateData',
  full_name='ghost.DataForContextReasoning.TemplateData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ghost.DataForContextReasoning.TemplateData.value', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=779,
  serialized_end=808,
)

_DATAFORCONTEXTREASONING = _descriptor.Descriptor(
  name='DataForContextReasoning',
  full_name='ghost.DataForContextReasoning',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='new_data', full_name='ghost.DataForContextReasoning.new_data', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='template_data', full_name='ghost.DataForContextReasoning.template_data', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATAFORCONTEXTREASONING_NEWDATA, _DATAFORCONTEXTREASONING_TEMPLATEDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=600,
  serialized_end=808,
)


_FULLDATA = _descriptor.Descriptor(
  name='FullData',
  full_name='ghost.FullData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reduced_data', full_name='ghost.FullData.reduced_data', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='training_data', full_name='ghost.FullData.training_data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=810,
  serialized_end=905,
)

_CR_CE_DEVICES_IP_DEVICES.containing_type = _CR_CE_DEVICES
_CR_CE_DEVICES_BLUETOOTH_DEVICES.containing_type = _CR_CE_DEVICES
_CR_CE_DEVICES_ZWAVE_DEVICES.containing_type = _CR_CE_DEVICES
_CR_CE_DEVICES_RF869_DEVICES.containing_type = _CR_CE_DEVICES
_CR_CE_DEVICES_ZIGBEE_DEVICES.containing_type = _CR_CE_DEVICES
_CR_CE_DEVICES.fields_by_name['ip_devices'].message_type = _CR_CE_DEVICES_IP_DEVICES
_CR_CE_DEVICES.fields_by_name['bt_devices'].message_type = _CR_CE_DEVICES_BLUETOOTH_DEVICES
_CR_CE_DEVICES.fields_by_name['zw_devices'].message_type = _CR_CE_DEVICES_ZWAVE_DEVICES
_CR_CE_DEVICES.fields_by_name['rf_devices'].message_type = _CR_CE_DEVICES_RF869_DEVICES
_CR_CE_DEVICES.fields_by_name['zb_devices'].message_type = _CR_CE_DEVICES_ZIGBEE_DEVICES
_REDUCEDDATA_DEVICEDATA.containing_type = _REDUCEDDATA
_REDUCEDDATA.fields_by_name['device_data'].message_type = _REDUCEDDATA_DEVICEDATA
_DATAFORCONTEXTREASONING_NEWDATA.containing_type = _DATAFORCONTEXTREASONING
_DATAFORCONTEXTREASONING_TEMPLATEDATA.containing_type = _DATAFORCONTEXTREASONING
_DATAFORCONTEXTREASONING.fields_by_name['new_data'].message_type = _DATAFORCONTEXTREASONING_NEWDATA
_DATAFORCONTEXTREASONING.fields_by_name['template_data'].message_type = _DATAFORCONTEXTREASONING_TEMPLATEDATA
_FULLDATA.fields_by_name['reduced_data'].message_type = _REDUCEDDATA
_FULLDATA.fields_by_name['training_data'].message_type = _REDUCEDDATA
DESCRIPTOR.message_types_by_name['CR_CE_Devices'] = _CR_CE_DEVICES
DESCRIPTOR.message_types_by_name['ReducedData'] = _REDUCEDDATA
DESCRIPTOR.message_types_by_name['DataForContextReasoning'] = _DATAFORCONTEXTREASONING
DESCRIPTOR.message_types_by_name['FullData'] = _FULLDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CR_CE_Devices = _reflection.GeneratedProtocolMessageType('CR_CE_Devices', (_message.Message,), {

  'IP_Devices' : _reflection.GeneratedProtocolMessageType('IP_Devices', (_message.Message,), {
    'DESCRIPTOR' : _CR_CE_DEVICES_IP_DEVICES,
    '__module__' : 'ghost_protocol.cr_ce_pb2'
    # @@protoc_insertion_point(class_scope:ghost.CR_CE_Devices.IP_Devices)
    })
  ,

  'Bluetooth_Devices' : _reflection.GeneratedProtocolMessageType('Bluetooth_Devices', (_message.Message,), {
    'DESCRIPTOR' : _CR_CE_DEVICES_BLUETOOTH_DEVICES,
    '__module__' : 'ghost_protocol.cr_ce_pb2'
    # @@protoc_insertion_point(class_scope:ghost.CR_CE_Devices.Bluetooth_Devices)
    })
  ,

  'ZWave_Devices' : _reflection.GeneratedProtocolMessageType('ZWave_Devices', (_message.Message,), {
    'DESCRIPTOR' : _CR_CE_DEVICES_ZWAVE_DEVICES,
    '__module__' : 'ghost_protocol.cr_ce_pb2'
    # @@protoc_insertion_point(class_scope:ghost.CR_CE_Devices.ZWave_Devices)
    })
  ,

  'RF869_Devices' : _reflection.GeneratedProtocolMessageType('RF869_Devices', (_message.Message,), {
    'DESCRIPTOR' : _CR_CE_DEVICES_RF869_DEVICES,
    '__module__' : 'ghost_protocol.cr_ce_pb2'
    # @@protoc_insertion_point(class_scope:ghost.CR_CE_Devices.RF869_Devices)
    })
  ,

  'Zigbee_Devices' : _reflection.GeneratedProtocolMessageType('Zigbee_Devices', (_message.Message,), {
    'DESCRIPTOR' : _CR_CE_DEVICES_ZIGBEE_DEVICES,
    '__module__' : 'ghost_protocol.cr_ce_pb2'
    # @@protoc_insertion_point(class_scope:ghost.CR_CE_Devices.Zigbee_Devices)
    })
  ,
  'DESCRIPTOR' : _CR_CE_DEVICES,
  '__module__' : 'ghost_protocol.cr_ce_pb2'
  # @@protoc_insertion_point(class_scope:ghost.CR_CE_Devices)
  })
_sym_db.RegisterMessage(CR_CE_Devices)
_sym_db.RegisterMessage(CR_CE_Devices.IP_Devices)
_sym_db.RegisterMessage(CR_CE_Devices.Bluetooth_Devices)
_sym_db.RegisterMessage(CR_CE_Devices.ZWave_Devices)
_sym_db.RegisterMessage(CR_CE_Devices.RF869_Devices)
_sym_db.RegisterMessage(CR_CE_Devices.Zigbee_Devices)

ReducedData = _reflection.GeneratedProtocolMessageType('ReducedData', (_message.Message,), {

  'DeviceData' : _reflection.GeneratedProtocolMessageType('DeviceData', (_message.Message,), {
    'DESCRIPTOR' : _REDUCEDDATA_DEVICEDATA,
    '__module__' : 'ghost_protocol.cr_ce_pb2'
    # @@protoc_insertion_point(class_scope:ghost.ReducedData.DeviceData)
    })
  ,
  'DESCRIPTOR' : _REDUCEDDATA,
  '__module__' : 'ghost_protocol.cr_ce_pb2'
  # @@protoc_insertion_point(class_scope:ghost.ReducedData)
  })
_sym_db.RegisterMessage(ReducedData)
_sym_db.RegisterMessage(ReducedData.DeviceData)

DataForContextReasoning = _reflection.GeneratedProtocolMessageType('DataForContextReasoning', (_message.Message,), {

  'NewData' : _reflection.GeneratedProtocolMessageType('NewData', (_message.Message,), {
    'DESCRIPTOR' : _DATAFORCONTEXTREASONING_NEWDATA,
    '__module__' : 'ghost_protocol.cr_ce_pb2'
    # @@protoc_insertion_point(class_scope:ghost.DataForContextReasoning.NewData)
    })
  ,

  'TemplateData' : _reflection.GeneratedProtocolMessageType('TemplateData', (_message.Message,), {
    'DESCRIPTOR' : _DATAFORCONTEXTREASONING_TEMPLATEDATA,
    '__module__' : 'ghost_protocol.cr_ce_pb2'
    # @@protoc_insertion_point(class_scope:ghost.DataForContextReasoning.TemplateData)
    })
  ,
  'DESCRIPTOR' : _DATAFORCONTEXTREASONING,
  '__module__' : 'ghost_protocol.cr_ce_pb2'
  # @@protoc_insertion_point(class_scope:ghost.DataForContextReasoning)
  })
_sym_db.RegisterMessage(DataForContextReasoning)
_sym_db.RegisterMessage(DataForContextReasoning.NewData)
_sym_db.RegisterMessage(DataForContextReasoning.TemplateData)

FullData = _reflection.GeneratedProtocolMessageType('FullData', (_message.Message,), {
  'DESCRIPTOR' : _FULLDATA,
  '__module__' : 'ghost_protocol.cr_ce_pb2'
  # @@protoc_insertion_point(class_scope:ghost.FullData)
  })
_sym_db.RegisterMessage(FullData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
