# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/ndfa.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ghost_protocol import inter_pb2 as ghost__protocol_dot_inter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/ndfa.proto',
  package='ghost',
  syntax='proto2',
  serialized_options=b'\n\032eu.ghost_iot.communication',
  serialized_pb=b'\n\x19ghost_protocol/ndfa.proto\x12\x05ghost\x1a\x1aghost_protocol/inter.proto\"\x9c\x01\n\x0e\x46ileProcessing\x12\x33\n\nalert_type\x18\x01 \x02(\x0e\x32\x1f.ghost.FileProcessing.AlertType\x12!\n\x05if_id\x18\x02 \x02(\x0b\x32\x12.ghost.InterfaceId\x12\x11\n\tfile_name\x18\x03 \x02(\t\"\x1f\n\tAlertType\x12\t\n\x05\x42\x45GIN\x10\x00\x12\x07\n\x03\x45ND\x10\x01\"\xe1\x01\n\tFlowAdded\x12!\n\x05if_id\x18\x01 \x02(\x0b\x32\x12.ghost.InterfaceId\x12\x0f\n\x07\x66low_id\x18\x02 \x02(\x05\x12\x13\n\x0bsrc_address\x18\x03 \x02(\t\x12\x13\n\x0b\x64st_address\x18\x04 \x02(\t\x12\x15\n\rtotal_bytes_a\x18\x05 \x02(\x05\x12\x11\n\tpackets_a\x18\x06 \x02(\x05\x12\x15\n\rtotal_bytes_b\x18\x07 \x02(\x05\x12\x11\n\tpackets_b\x18\x08 \x02(\x05\x12\"\n\x04type\x18\t \x02(\x0e\x32\x14.ghost.InterfaceType\"<\n\rNewExternalIp\x12\x12\n\nip_address\x18\x01 \x02(\t\x12\x17\n\x0f\x65vent_timestamp\x18\x02 \x01(\x01\"|\n\tNewDevice\x12!\n\x05if_id\x18\x01 \x02(\x0b\x32\x12.ghost.InterfaceId\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x02(\t\x12\"\n\x04type\x18\x03 \x02(\x0e\x32\x14.ghost.InterfaceType\x12\x17\n\x0f\x65vent_timestamp\x18\x04 \x01(\x01\"\x94\x01\n\x0bPrivateData\x12!\n\x05if_id\x18\x01 \x02(\x0b\x32\x12.ghost.InterfaceId\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x02(\t\x12\"\n\x04type\x18\x03 \x02(\x0e\x32\x14.ghost.InterfaceType\x12\x14\n\x0cprivate_data\x18\x04 \x02(\t\x12\x17\n\x0f\x65vent_timestamp\x18\x05 \x01(\x01\x42\x1c\n\x1a\x65u.ghost_iot.communication'
  ,
  dependencies=[ghost__protocol_dot_inter__pb2.DESCRIPTOR,])



_FILEPROCESSING_ALERTTYPE = _descriptor.EnumDescriptor(
  name='AlertType',
  full_name='ghost.FileProcessing.AlertType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BEGIN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='END', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=190,
  serialized_end=221,
)
_sym_db.RegisterEnumDescriptor(_FILEPROCESSING_ALERTTYPE)


_FILEPROCESSING = _descriptor.Descriptor(
  name='FileProcessing',
  full_name='ghost.FileProcessing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alert_type', full_name='ghost.FileProcessing.alert_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='if_id', full_name='ghost.FileProcessing.if_id', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='ghost.FileProcessing.file_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FILEPROCESSING_ALERTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=221,
)


_FLOWADDED = _descriptor.Descriptor(
  name='FlowAdded',
  full_name='ghost.FlowAdded',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='if_id', full_name='ghost.FlowAdded.if_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flow_id', full_name='ghost.FlowAdded.flow_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src_address', full_name='ghost.FlowAdded.src_address', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_address', full_name='ghost.FlowAdded.dst_address', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_bytes_a', full_name='ghost.FlowAdded.total_bytes_a', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packets_a', full_name='ghost.FlowAdded.packets_a', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_bytes_b', full_name='ghost.FlowAdded.total_bytes_b', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packets_b', full_name='ghost.FlowAdded.packets_b', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ghost.FlowAdded.type', index=8,
      number=9, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=449,
)


_NEWEXTERNALIP = _descriptor.Descriptor(
  name='NewExternalIp',
  full_name='ghost.NewExternalIp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip_address', full_name='ghost.NewExternalIp.ip_address', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_timestamp', full_name='ghost.NewExternalIp.event_timestamp', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=511,
)


_NEWDEVICE = _descriptor.Descriptor(
  name='NewDevice',
  full_name='ghost.NewDevice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='if_id', full_name='ghost.NewDevice.if_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='ghost.NewDevice.address', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ghost.NewDevice.type', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_timestamp', full_name='ghost.NewDevice.event_timestamp', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=513,
  serialized_end=637,
)


_PRIVATEDATA = _descriptor.Descriptor(
  name='PrivateData',
  full_name='ghost.PrivateData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='if_id', full_name='ghost.PrivateData.if_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='ghost.PrivateData.address', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='ghost.PrivateData.type', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='private_data', full_name='ghost.PrivateData.private_data', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_timestamp', full_name='ghost.PrivateData.event_timestamp', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=640,
  serialized_end=788,
)

_FILEPROCESSING.fields_by_name['alert_type'].enum_type = _FILEPROCESSING_ALERTTYPE
_FILEPROCESSING.fields_by_name['if_id'].message_type = ghost__protocol_dot_inter__pb2._INTERFACEID
_FILEPROCESSING_ALERTTYPE.containing_type = _FILEPROCESSING
_FLOWADDED.fields_by_name['if_id'].message_type = ghost__protocol_dot_inter__pb2._INTERFACEID
_FLOWADDED.fields_by_name['type'].enum_type = ghost__protocol_dot_inter__pb2._INTERFACETYPE
_NEWDEVICE.fields_by_name['if_id'].message_type = ghost__protocol_dot_inter__pb2._INTERFACEID
_NEWDEVICE.fields_by_name['type'].enum_type = ghost__protocol_dot_inter__pb2._INTERFACETYPE
_PRIVATEDATA.fields_by_name['if_id'].message_type = ghost__protocol_dot_inter__pb2._INTERFACEID
_PRIVATEDATA.fields_by_name['type'].enum_type = ghost__protocol_dot_inter__pb2._INTERFACETYPE
DESCRIPTOR.message_types_by_name['FileProcessing'] = _FILEPROCESSING
DESCRIPTOR.message_types_by_name['FlowAdded'] = _FLOWADDED
DESCRIPTOR.message_types_by_name['NewExternalIp'] = _NEWEXTERNALIP
DESCRIPTOR.message_types_by_name['NewDevice'] = _NEWDEVICE
DESCRIPTOR.message_types_by_name['PrivateData'] = _PRIVATEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileProcessing = _reflection.GeneratedProtocolMessageType('FileProcessing', (_message.Message,), {
  'DESCRIPTOR' : _FILEPROCESSING,
  '__module__' : 'ghost_protocol.ndfa_pb2'
  # @@protoc_insertion_point(class_scope:ghost.FileProcessing)
  })
_sym_db.RegisterMessage(FileProcessing)

FlowAdded = _reflection.GeneratedProtocolMessageType('FlowAdded', (_message.Message,), {
  'DESCRIPTOR' : _FLOWADDED,
  '__module__' : 'ghost_protocol.ndfa_pb2'
  # @@protoc_insertion_point(class_scope:ghost.FlowAdded)
  })
_sym_db.RegisterMessage(FlowAdded)

NewExternalIp = _reflection.GeneratedProtocolMessageType('NewExternalIp', (_message.Message,), {
  'DESCRIPTOR' : _NEWEXTERNALIP,
  '__module__' : 'ghost_protocol.ndfa_pb2'
  # @@protoc_insertion_point(class_scope:ghost.NewExternalIp)
  })
_sym_db.RegisterMessage(NewExternalIp)

NewDevice = _reflection.GeneratedProtocolMessageType('NewDevice', (_message.Message,), {
  'DESCRIPTOR' : _NEWDEVICE,
  '__module__' : 'ghost_protocol.ndfa_pb2'
  # @@protoc_insertion_point(class_scope:ghost.NewDevice)
  })
_sym_db.RegisterMessage(NewDevice)

PrivateData = _reflection.GeneratedProtocolMessageType('PrivateData', (_message.Message,), {
  'DESCRIPTOR' : _PRIVATEDATA,
  '__module__' : 'ghost_protocol.ndfa_pb2'
  # @@protoc_insertion_point(class_scope:ghost.PrivateData)
  })
_sym_db.RegisterMessage(PrivateData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
