# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/profile_building.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/profile_building.proto',
  package='ghost',
  syntax='proto2',
  serialized_pb=_b('\n%ghost_protocol/profile_building.proto\x12\x05ghost\"V\n\x05\x42Node\x12\n\n\x02id\x18\x01 \x02(\x04\x12\r\n\x05mac_a\x18\x02 \x02(\t\x12\r\n\x05mac_b\x18\x03 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x02(\t\x12\x15\n\rprotocol_type\x18\x05 \x02(\t\"m\n\x05\x42\x45\x64ge\x12\n\n\x02id\x18\x01 \x02(\x04\x12\r\n\x05\x63ount\x18\x02 \x02(\x04\x12\x0e\n\x06node_1\x18\x03 \x02(\x04\x12\x0e\n\x06node_2\x18\x04 \x02(\x04\x12\x12\n\nmac_source\x18\x05 \x02(\t\x12\x15\n\rprotocol_type\x18\x06 \x02(\t\"@\n\x06\x42Graph\x12\x1a\n\x04node\x18\x01 \x03(\x0b\x32\x0c.ghost.BNode\x12\x1a\n\x04\x65\x64ge\x18\x02 \x03(\x0b\x32\x0c.ghost.BEdge\"!\n\rMac_Addresses\x12\x10\n\x08mac_addr\x18\x01 \x03(\t\"T\n\x1cInitialize_Update_timestamps\x12\x1a\n\x12starting_timestamp\x18\x01 \x01(\x01\x12\x18\n\x10\x65nding_timestamp\x18\x02 \x01(\x01\"$\n\x11PB_Reply_Messages\x12\x0f\n\x07message\x18\x01 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BNODE = _descriptor.Descriptor(
  name='BNode',
  full_name='ghost.BNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ghost.BNode.id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mac_a', full_name='ghost.BNode.mac_a', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mac_b', full_name='ghost.BNode.mac_b', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='ghost.BNode.data', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protocol_type', full_name='ghost.BNode.protocol_type', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=134,
)


_BEDGE = _descriptor.Descriptor(
  name='BEdge',
  full_name='ghost.BEdge',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ghost.BEdge.id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='ghost.BEdge.count', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_1', full_name='ghost.BEdge.node_1', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_2', full_name='ghost.BEdge.node_2', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mac_source', full_name='ghost.BEdge.mac_source', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protocol_type', full_name='ghost.BEdge.protocol_type', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=245,
)


_BGRAPH = _descriptor.Descriptor(
  name='BGraph',
  full_name='ghost.BGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='ghost.BGraph.node', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='edge', full_name='ghost.BGraph.edge', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=311,
)


_MAC_ADDRESSES = _descriptor.Descriptor(
  name='Mac_Addresses',
  full_name='ghost.Mac_Addresses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mac_addr', full_name='ghost.Mac_Addresses.mac_addr', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=346,
)


_INITIALIZE_UPDATE_TIMESTAMPS = _descriptor.Descriptor(
  name='Initialize_Update_timestamps',
  full_name='ghost.Initialize_Update_timestamps',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='starting_timestamp', full_name='ghost.Initialize_Update_timestamps.starting_timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ending_timestamp', full_name='ghost.Initialize_Update_timestamps.ending_timestamp', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=432,
)


_PB_REPLY_MESSAGES = _descriptor.Descriptor(
  name='PB_Reply_Messages',
  full_name='ghost.PB_Reply_Messages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ghost.PB_Reply_Messages.message', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=470,
)

_BGRAPH.fields_by_name['node'].message_type = _BNODE
_BGRAPH.fields_by_name['edge'].message_type = _BEDGE
DESCRIPTOR.message_types_by_name['BNode'] = _BNODE
DESCRIPTOR.message_types_by_name['BEdge'] = _BEDGE
DESCRIPTOR.message_types_by_name['BGraph'] = _BGRAPH
DESCRIPTOR.message_types_by_name['Mac_Addresses'] = _MAC_ADDRESSES
DESCRIPTOR.message_types_by_name['Initialize_Update_timestamps'] = _INITIALIZE_UPDATE_TIMESTAMPS
DESCRIPTOR.message_types_by_name['PB_Reply_Messages'] = _PB_REPLY_MESSAGES

BNode = _reflection.GeneratedProtocolMessageType('BNode', (_message.Message,), dict(
  DESCRIPTOR = _BNODE,
  __module__ = 'ghost_protocol.profile_building_pb2'
  # @@protoc_insertion_point(class_scope:ghost.BNode)
  ))
_sym_db.RegisterMessage(BNode)

BEdge = _reflection.GeneratedProtocolMessageType('BEdge', (_message.Message,), dict(
  DESCRIPTOR = _BEDGE,
  __module__ = 'ghost_protocol.profile_building_pb2'
  # @@protoc_insertion_point(class_scope:ghost.BEdge)
  ))
_sym_db.RegisterMessage(BEdge)

BGraph = _reflection.GeneratedProtocolMessageType('BGraph', (_message.Message,), dict(
  DESCRIPTOR = _BGRAPH,
  __module__ = 'ghost_protocol.profile_building_pb2'
  # @@protoc_insertion_point(class_scope:ghost.BGraph)
  ))
_sym_db.RegisterMessage(BGraph)

Mac_Addresses = _reflection.GeneratedProtocolMessageType('Mac_Addresses', (_message.Message,), dict(
  DESCRIPTOR = _MAC_ADDRESSES,
  __module__ = 'ghost_protocol.profile_building_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Mac_Addresses)
  ))
_sym_db.RegisterMessage(Mac_Addresses)

Initialize_Update_timestamps = _reflection.GeneratedProtocolMessageType('Initialize_Update_timestamps', (_message.Message,), dict(
  DESCRIPTOR = _INITIALIZE_UPDATE_TIMESTAMPS,
  __module__ = 'ghost_protocol.profile_building_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Initialize_Update_timestamps)
  ))
_sym_db.RegisterMessage(Initialize_Update_timestamps)

PB_Reply_Messages = _reflection.GeneratedProtocolMessageType('PB_Reply_Messages', (_message.Message,), dict(
  DESCRIPTOR = _PB_REPLY_MESSAGES,
  __module__ = 'ghost_protocol.profile_building_pb2'
  # @@protoc_insertion_point(class_scope:ghost.PB_Reply_Messages)
  ))
_sym_db.RegisterMessage(PB_Reply_Messages)


# @@protoc_insertion_point(module_scope)
