# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/sc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ghost_protocol import inter_pb2 as ghost__protocol_dot_inter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/sc.proto',
  package='ghost',
  syntax='proto2',
  serialized_options=b'\n\032eu.ghost_iot.communication',
  serialized_pb=b'\n\x17ghost_protocol/sc.proto\x12\x05ghost\x1a\x1aghost_protocol/inter.proto\"\x10\n\x02Ip\x12\n\n\x02ip\x18\x01 \x02(\t\"\x1a\n\x0cReport_ip_ok\x12\n\n\x02ok\x18\x01 \x02(\x08\"\x19\n\x08Ip_score\x12\r\n\x05score\x18\x01 \x02(\x01\"#\n\x07Ip_list\x12\n\n\x02ip\x18\x01 \x02(\t\x12\x0c\n\x04list\x18\x02 \x02(\x08\"/\n\x0bIp_presence\x12\x0e\n\x06status\x18\x01 \x02(\x08\x12\x10\n\x08presence\x18\x02 \x02(\x08\"0\n\tintegrity\x12\x10\n\x08response\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x02(\t\"Y\n\x0f\x44\x65viceIntegrity\x12\x10\n\x08response\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x02(\t\x12!\n\x08\x64\x65viceid\x18\x03 \x02(\x0b\x32\x0f.ghost.DeviceId\"\x16\n\x06method\x12\x0c\n\x04\x64\x61ta\x18\x01 \x02(\tB\x1c\n\x1a\x65u.ghost_iot.communication'
  ,
  dependencies=[ghost__protocol_dot_inter__pb2.DESCRIPTOR,])




_IP = _descriptor.Descriptor(
  name='Ip',
  full_name='ghost.Ip',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='ghost.Ip.ip', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=78,
)


_REPORT_IP_OK = _descriptor.Descriptor(
  name='Report_ip_ok',
  full_name='ghost.Report_ip_ok',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='ghost.Report_ip_ok.ok', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=106,
)


_IP_SCORE = _descriptor.Descriptor(
  name='Ip_score',
  full_name='ghost.Ip_score',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='ghost.Ip_score.score', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=133,
)


_IP_LIST = _descriptor.Descriptor(
  name='Ip_list',
  full_name='ghost.Ip_list',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='ghost.Ip_list.ip', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list', full_name='ghost.Ip_list.list', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=170,
)


_IP_PRESENCE = _descriptor.Descriptor(
  name='Ip_presence',
  full_name='ghost.Ip_presence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ghost.Ip_presence.status', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='presence', full_name='ghost.Ip_presence.presence', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=219,
)


_INTEGRITY = _descriptor.Descriptor(
  name='integrity',
  full_name='ghost.integrity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='ghost.integrity.response', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ghost.integrity.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=269,
)


_DEVICEINTEGRITY = _descriptor.Descriptor(
  name='DeviceIntegrity',
  full_name='ghost.DeviceIntegrity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='ghost.DeviceIntegrity.response', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ghost.DeviceIntegrity.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deviceid', full_name='ghost.DeviceIntegrity.deviceid', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=360,
)


_METHOD = _descriptor.Descriptor(
  name='method',
  full_name='ghost.method',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ghost.method.data', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=384,
)

_DEVICEINTEGRITY.fields_by_name['deviceid'].message_type = ghost__protocol_dot_inter__pb2._DEVICEID
DESCRIPTOR.message_types_by_name['Ip'] = _IP
DESCRIPTOR.message_types_by_name['Report_ip_ok'] = _REPORT_IP_OK
DESCRIPTOR.message_types_by_name['Ip_score'] = _IP_SCORE
DESCRIPTOR.message_types_by_name['Ip_list'] = _IP_LIST
DESCRIPTOR.message_types_by_name['Ip_presence'] = _IP_PRESENCE
DESCRIPTOR.message_types_by_name['integrity'] = _INTEGRITY
DESCRIPTOR.message_types_by_name['DeviceIntegrity'] = _DEVICEINTEGRITY
DESCRIPTOR.message_types_by_name['method'] = _METHOD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ip = _reflection.GeneratedProtocolMessageType('Ip', (_message.Message,), {
  'DESCRIPTOR' : _IP,
  '__module__' : 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Ip)
  })
_sym_db.RegisterMessage(Ip)

Report_ip_ok = _reflection.GeneratedProtocolMessageType('Report_ip_ok', (_message.Message,), {
  'DESCRIPTOR' : _REPORT_IP_OK,
  '__module__' : 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Report_ip_ok)
  })
_sym_db.RegisterMessage(Report_ip_ok)

Ip_score = _reflection.GeneratedProtocolMessageType('Ip_score', (_message.Message,), {
  'DESCRIPTOR' : _IP_SCORE,
  '__module__' : 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Ip_score)
  })
_sym_db.RegisterMessage(Ip_score)

Ip_list = _reflection.GeneratedProtocolMessageType('Ip_list', (_message.Message,), {
  'DESCRIPTOR' : _IP_LIST,
  '__module__' : 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Ip_list)
  })
_sym_db.RegisterMessage(Ip_list)

Ip_presence = _reflection.GeneratedProtocolMessageType('Ip_presence', (_message.Message,), {
  'DESCRIPTOR' : _IP_PRESENCE,
  '__module__' : 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.Ip_presence)
  })
_sym_db.RegisterMessage(Ip_presence)

integrity = _reflection.GeneratedProtocolMessageType('integrity', (_message.Message,), {
  'DESCRIPTOR' : _INTEGRITY,
  '__module__' : 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.integrity)
  })
_sym_db.RegisterMessage(integrity)

DeviceIntegrity = _reflection.GeneratedProtocolMessageType('DeviceIntegrity', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEINTEGRITY,
  '__module__' : 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.DeviceIntegrity)
  })
_sym_db.RegisterMessage(DeviceIntegrity)

method = _reflection.GeneratedProtocolMessageType('method', (_message.Message,), {
  'DESCRIPTOR' : _METHOD,
  '__module__' : 'ghost_protocol.sc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.method)
  })
_sym_db.RegisterMessage(method)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
