# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/spr.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/spr.proto',
  package='ghost',
  syntax='proto2',
  serialized_options=b'\n\032eu.ghost_iot.communication',
  serialized_pb=b'\n\x18ghost_protocol/spr.proto\x12\x05ghost\"\xc8\x01\n\tIPTHREATS\x12\n\n\x02IP\x18\x01 \x02(\t\x12(\n\x07Threats\x18\x02 \x03(\x0b\x32\x17.ghost.IPTHREATS.THREAT\x1a\x84\x01\n\x06THREAT\x12\x19\n\x11\x61ttackDescription\x18\x01 \x02(\t\x12\x12\n\nattackType\x18\x02 \x02(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x02(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x02(\t\x12\x0e\n\x06\x64omain\x18\x05 \x02(\t\x12\x0e\n\x06source\x18\x06 \x02(\t\x12\x0c\n\x04time\x18\x07 \x02(\t\"C\n\x10GraphProbability\x12\x10\n\x08protocol\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x01\x12\x0e\n\x06period\x18\x03 \x02(\tB\x1c\n\x1a\x65u.ghost_iot.communication'
)




_IPTHREATS_THREAT = _descriptor.Descriptor(
  name='THREAT',
  full_name='ghost.IPTHREATS.THREAT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attackDescription', full_name='ghost.IPTHREATS.THREAT.attackDescription', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attackType', full_name='ghost.IPTHREATS.THREAT.attackType', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='ghost.IPTHREATS.THREAT.country', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='ghost.IPTHREATS.THREAT.date', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain', full_name='ghost.IPTHREATS.THREAT.domain', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='ghost.IPTHREATS.THREAT.source', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='ghost.IPTHREATS.THREAT.time', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=236,
)

_IPTHREATS = _descriptor.Descriptor(
  name='IPTHREATS',
  full_name='ghost.IPTHREATS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='IP', full_name='ghost.IPTHREATS.IP', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Threats', full_name='ghost.IPTHREATS.Threats', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_IPTHREATS_THREAT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=236,
)


_GRAPHPROBABILITY = _descriptor.Descriptor(
  name='GraphProbability',
  full_name='ghost.GraphProbability',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protocol', full_name='ghost.GraphProbability.protocol', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ghost.GraphProbability.value', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='period', full_name='ghost.GraphProbability.period', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=305,
)

_IPTHREATS_THREAT.containing_type = _IPTHREATS
_IPTHREATS.fields_by_name['Threats'].message_type = _IPTHREATS_THREAT
DESCRIPTOR.message_types_by_name['IPTHREATS'] = _IPTHREATS
DESCRIPTOR.message_types_by_name['GraphProbability'] = _GRAPHPROBABILITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IPTHREATS = _reflection.GeneratedProtocolMessageType('IPTHREATS', (_message.Message,), {

  'THREAT' : _reflection.GeneratedProtocolMessageType('THREAT', (_message.Message,), {
    'DESCRIPTOR' : _IPTHREATS_THREAT,
    '__module__' : 'ghost_protocol.spr_pb2'
    # @@protoc_insertion_point(class_scope:ghost.IPTHREATS.THREAT)
    })
  ,
  'DESCRIPTOR' : _IPTHREATS,
  '__module__' : 'ghost_protocol.spr_pb2'
  # @@protoc_insertion_point(class_scope:ghost.IPTHREATS)
  })
_sym_db.RegisterMessage(IPTHREATS)
_sym_db.RegisterMessage(IPTHREATS.THREAT)

GraphProbability = _reflection.GeneratedProtocolMessageType('GraphProbability', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHPROBABILITY,
  '__module__' : 'ghost_protocol.spr_pb2'
  # @@protoc_insertion_point(class_scope:ghost.GraphProbability)
  })
_sym_db.RegisterMessage(GraphProbability)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
