# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/te_dc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ghost_protocol import inter_pb2 as ghost__protocol_dot_inter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/te_dc.proto',
  package='ghost',
  syntax='proto2',
  serialized_options=b'\n\032eu.ghost_iot.communication',
  serialized_pb=b'\n\x1aghost_protocol/te_dc.proto\x12\x05ghost\x1a\x1aghost_protocol/inter.proto\"\x8b\x01\n\x10\x41nomalyDetection\x12\x16\n\x0eseverity_score\x18\x01 \x02(\r\x12\x19\n\x11reliability_score\x18\x02 \x02(\r\x12!\n\x06\x64\x65vice\x18\x03 \x02(\x0b\x32\x11.ghost.DeviceInfo\x12\x11\n\ttimestamp\x18\x04 \x02(\t\x12\x0e\n\x06reason\x18\x05 \x02(\tB\x1c\n\x1a\x65u.ghost_iot.communication'
  ,
  dependencies=[ghost__protocol_dot_inter__pb2.DESCRIPTOR,])




_ANOMALYDETECTION = _descriptor.Descriptor(
  name='AnomalyDetection',
  full_name='ghost.AnomalyDetection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='severity_score', full_name='ghost.AnomalyDetection.severity_score', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reliability_score', full_name='ghost.AnomalyDetection.reliability_score', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device', full_name='ghost.AnomalyDetection.device', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ghost.AnomalyDetection.timestamp', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reason', full_name='ghost.AnomalyDetection.reason', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=205,
)

_ANOMALYDETECTION.fields_by_name['device'].message_type = ghost__protocol_dot_inter__pb2._DEVICEINFO
DESCRIPTOR.message_types_by_name['AnomalyDetection'] = _ANOMALYDETECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnomalyDetection = _reflection.GeneratedProtocolMessageType('AnomalyDetection', (_message.Message,), {
  'DESCRIPTOR' : _ANOMALYDETECTION,
  '__module__' : 'ghost_protocol.te_dc_pb2'
  # @@protoc_insertion_point(class_scope:ghost.AnomalyDetection)
  })
_sym_db.RegisterMessage(AnomalyDetection)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
