# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/te.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ghost_protocol import inter_pb2 as ghost__protocol_dot_inter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/te.proto',
  package='ghost',
  syntax='proto2',
  serialized_pb=_b('\n\x17ghost_protocol/te.proto\x12\x05ghost\x1a\x1aghost_protocol/inter.proto\"\xa2\x02\n\x14\x63ybersecurity_status\x12!\n\x05if_id\x18\x01 \x02(\x0b\x32\x12.ghost.InterfaceId\x12\x0f\n\x07id_slot\x18\x02 \x02(\x05\x12\x14\n\x0c\x61ttack_proba\x18\x03 \x02(\x02\x12\x12\n\nstart_time\x18\x04 \x02(\x01\x12\x10\n\x08\x65nd_time\x18\x05 \x02(\x01\x12\x17\n\x0f\x61ttack_ID_top_1\x18\x06 \x01(\x05\x12\x19\n\x11\x61ttack_prob_top_1\x18\x07 \x01(\x02\x12\x17\n\x0f\x61ttack_ID_top_2\x18\x08 \x01(\x05\x12\x19\n\x11\x61ttack_prob_top_2\x18\t \x01(\x02\x12\x17\n\x0f\x61ttack_ID_top_3\x18\n \x01(\x05\x12\x19\n\x11\x61ttack_prob_top_3\x18\x0b \x01(\x02\x42\x1c\n\x1a\x65u.ghost_iot.communication')
  ,
  dependencies=[ghost__protocol_dot_inter__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CYBERSECURITY_STATUS = _descriptor.Descriptor(
  name='cybersecurity_status',
  full_name='ghost.cybersecurity_status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='if_id', full_name='ghost.cybersecurity_status.if_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id_slot', full_name='ghost.cybersecurity_status.id_slot', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack_proba', full_name='ghost.cybersecurity_status.attack_proba', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='ghost.cybersecurity_status.start_time', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='ghost.cybersecurity_status.end_time', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack_ID_top_1', full_name='ghost.cybersecurity_status.attack_ID_top_1', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack_prob_top_1', full_name='ghost.cybersecurity_status.attack_prob_top_1', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack_ID_top_2', full_name='ghost.cybersecurity_status.attack_ID_top_2', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack_prob_top_2', full_name='ghost.cybersecurity_status.attack_prob_top_2', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack_ID_top_3', full_name='ghost.cybersecurity_status.attack_ID_top_3', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attack_prob_top_3', full_name='ghost.cybersecurity_status.attack_prob_top_3', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=353,
)

_CYBERSECURITY_STATUS.fields_by_name['if_id'].message_type = ghost__protocol_dot_inter__pb2._INTERFACEID
DESCRIPTOR.message_types_by_name['cybersecurity_status'] = _CYBERSECURITY_STATUS

cybersecurity_status = _reflection.GeneratedProtocolMessageType('cybersecurity_status', (_message.Message,), dict(
  DESCRIPTOR = _CYBERSECURITY_STATUS,
  __module__ = 'ghost_protocol.te_pb2'
  # @@protoc_insertion_point(class_scope:ghost.cybersecurity_status)
  ))
_sym_db.RegisterMessage(cybersecurity_status)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032eu.ghost_iot.communication'))
# @@protoc_insertion_point(module_scope)
